"""Comprehensive tests for quill-table-better format compatibility.

Tests cover all delta format variations generated by the quill-table-better
QuillJS module (https://github.com/attoae/quill-table-better), including:

- Basic table creation with table-temporary + table-cell-block + table-cell
- Colspan and rowspan (merged cells)
- In-cell headings via table-header
- In-cell lists via table-list / table-list-container
- Inline formatting within cells (bold, italic, links, etc.)
- Multiple paragraphs within a single cell
- Mixed content within cells (text, headings, lists)
- Cell styling (background-color, borders, alignment via style attribute)
- table-col column definitions
- Empty cells
- Single-row and single-column tables
- Large tables
- Tables mixed with surrounding content
"""

import unittest
from ncdeltaprocess import TranslatorQuillJS
from ncdeltaprocess.modules.table_better import (
    TableBetterModule,
    TableBetter2Block,
    TableBetter2RowBlock,
    TableBetter2CellBlock,
    TableBetter2CellHeadingBlock,
    TableBetter2CellListContainerBlock,
    TableBetter2CellListItemBlock,
)


def _make_translator():
    """Create a TranslatorQuillJS with quill-table-better module registered."""
    t = TranslatorQuillJS()
    t.add_module(TableBetterModule)
    return t


class TestBasicTable(unittest.TestCase):
    """Basic table creation from quill-table-better delta ops."""

    def test_simple_2x2_table(self):
        """A basic 2x2 table: table-temporary + 4 cells."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'A1'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-a1',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'B1'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-b1',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'A2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-a2',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'B2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-b2',
                'table-cell': {'data-row': 'row-2'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)
        self.assertIn('</table>', html)
        self.assertEqual(html.count('<tr>'), 2)
        self.assertEqual(html.count('<td>'), 4)
        self.assertIn('A1', html)
        self.assertIn('B1', html)
        self.assertIn('A2', html)
        self.assertIn('B2', html)

    def test_3x3_table(self):
        """A 3x3 table with content in every cell."""
        ops = [{'insert': '\n', 'attributes': {'table-temporary': True}}]
        for row_idx in range(1, 4):
            for col_idx in range(1, 4):
                ops.extend([
                    {'insert': f'R{row_idx}C{col_idx}'},
                    {'insert': '\n', 'attributes': {
                        'table-cell-block': f'cell-r{row_idx}c{col_idx}',
                        'table-cell': {'data-row': f'row-{row_idx}'},
                    }},
                ])
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertEqual(html.count('<tr>'), 3)
        self.assertEqual(html.count('<td>'), 9)
        for r in range(1, 4):
            for c in range(1, 4):
                self.assertIn(f'R{r}C{c}', html)

    def test_single_cell_table(self):
        """A 1x1 table with a single cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Only cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-only',
                'table-cell': {'data-row': 'row-only'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)
        self.assertEqual(html.count('<tr>'), 1)
        self.assertEqual(html.count('<td>'), 1)
        self.assertIn('Only cell', html)

    def test_single_row_table(self):
        """A table with one row and multiple columns."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Col1'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-c1',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Col2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-c2',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Col3'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-c3',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertEqual(html.count('<tr>'), 1)
        self.assertEqual(html.count('<td>'), 3)

    def test_single_column_table(self):
        """A table with one column and multiple rows."""
        ops = [{'insert': '\n', 'attributes': {'table-temporary': True}}]
        for r in range(1, 5):
            ops.extend([
                {'insert': f'Row {r}'},
                {'insert': '\n', 'attributes': {
                    'table-cell-block': f'cell-r{r}',
                    'table-cell': {'data-row': f'row-{r}'},
                }},
            ])
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertEqual(html.count('<tr>'), 4)
        self.assertEqual(html.count('<td>'), 4)


class TestTableTemporaryAttributes(unittest.TestCase):
    """Tests for table-temporary with various attribute combinations."""

    def test_table_temporary_true(self):
        """table-temporary: true (simplest form)."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)

    def test_table_temporary_with_style(self):
        """table-temporary with style attributes (border, width, etc.)."""
        ops = [
            {'insert': '\n', 'attributes': {
                'table-temporary': {
                    'style': 'width: 100%; border-style: solid; border-color: #000; border-width: 1px',
                    'border': '1',
                    'data-class': 'ql-table-better custom-class',
                }
            }},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)
        self.assertIn('Cell', html)

    def test_table_temporary_with_cellspacing(self):
        """table-temporary with cellspacing attribute."""
        ops = [
            {'insert': '\n', 'attributes': {
                'table-temporary': {
                    'cellspacing': '0',
                    'border': '0',
                }
            }},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)

    def test_table_temporary_empty_dict(self):
        """table-temporary: {} (empty dict)."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': {}}},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)


class TestEmptyCells(unittest.TestCase):
    """Tests for cells with no text content."""

    def test_empty_cell(self):
        """An empty cell (just the newline, no text insert before it)."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Filled'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-filled',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-empty',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertEqual(html.count('<td>'), 2)
        self.assertIn('Filled', html)

    def test_all_empty_cells(self):
        """A 2x2 table where every cell is empty."""
        ops = [{'insert': '\n', 'attributes': {'table-temporary': True}}]
        for row in ('row-1', 'row-2'):
            for cell_idx in range(2):
                ops.append(
                    {'insert': '\n', 'attributes': {
                        'table-cell-block': f'cell-{row}-{cell_idx}',
                        'table-cell': {'data-row': row},
                    }},
                )
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertEqual(html.count('<tr>'), 2)
        self.assertEqual(html.count('<td>'), 4)


class TestColspanRowspan(unittest.TestCase):
    """Tests for merged cells with colspan and rowspan."""

    def test_colspan(self):
        """A cell spanning 2 columns."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            # Row 1: single cell spanning 2 columns
            {'insert': 'Wide cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-wide',
                'table-cell': {'data-row': 'row-1', 'colspan': '2'},
            }},
            # Row 2: two normal cells
            {'insert': 'Left'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-left',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'Right'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-right',
                'table-cell': {'data-row': 'row-2'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('colspan="2"', html)
        self.assertIn('Wide cell', html)

    def test_rowspan(self):
        """A cell spanning 2 rows."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            # Row 1, cell 1: spans 2 rows
            {'insert': 'Tall cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-tall',
                'table-cell': {'data-row': 'row-1', 'rowspan': '2'},
            }},
            {'insert': 'R1C2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r1c2',
                'table-cell': {'data-row': 'row-1'},
            }},
            # Row 2 only has one cell (the other is spanned)
            {'insert': 'R2C2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r2c2',
                'table-cell': {'data-row': 'row-2'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('rowspan="2"', html)
        self.assertIn('Tall cell', html)

    def test_colspan_and_rowspan(self):
        """A cell spanning both columns and rows."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Merged'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-merged',
                'table-cell': {'data-row': 'row-1', 'colspan': '2', 'rowspan': '2'},
            }},
            {'insert': 'R1C3'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r1c3',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'R2C3'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r2c3',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'R3C1'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r3c1',
                'table-cell': {'data-row': 'row-3'},
            }},
            {'insert': 'R3C2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r3c2',
                'table-cell': {'data-row': 'row-3'},
            }},
            {'insert': 'R3C3'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r3c3',
                'table-cell': {'data-row': 'row-3'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('colspan="2"', html)
        self.assertIn('rowspan="2"', html)
        self.assertIn('Merged', html)

    def test_colspan_1_not_rendered(self):
        """colspan=1 should not produce a colspan attribute in HTML."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1', 'colspan': '1', 'rowspan': '1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertNotIn('colspan', html)
        self.assertNotIn('rowspan', html)

    def test_colspan_as_integer(self):
        """colspan/rowspan provided as integer rather than string."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Wide'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-wide',
                'table-cell': {'data-row': 'row-1', 'colspan': 3},
            }},
            # Row 2 with 3 cells
            {'insert': 'A'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-a',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'B'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-b',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'C'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-c',
                'table-cell': {'data-row': 'row-2'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('colspan="3"', html)


class TestInCellHeaders(unittest.TestCase):
    """Tests for heading blocks inside table cells (table-header attribute)."""

    def test_heading_in_cell(self):
        """A table-header block inside a cell creates a heading block."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Title'},
            {'insert': '\n', 'attributes': {
                'table-header': {'cellId': 'cell-h1', 'value': 1},
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Normal'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-n1',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)
        self.assertIn('Title', html)
        self.assertIn('Normal', html)

    def test_heading_with_colspan(self):
        """A heading in a cell that spans multiple columns."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Big Title'},
            {'insert': '\n', 'attributes': {
                'table-header': {'cellId': 'cell-bh', 'colspan': '3', 'rowspan': '1'},
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'A'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-a',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'B'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-b',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'C'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-c',
                'table-cell': {'data-row': 'row-2'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Big Title', html)
        self.assertEqual(html.count('<tr>'), 2)

    def test_multiple_headings_in_cell(self):
        """Multiple heading blocks within the same cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Heading 1'},
            {'insert': '\n', 'attributes': {
                'table-header': {'cellId': 'cell-h', 'value': 1},
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Heading 2'},
            {'insert': '\n', 'attributes': {
                'table-header': {'cellId': 'cell-h', 'value': 2},
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Heading 1', html)
        self.assertIn('Heading 2', html)
        self.assertEqual(html.count('<td>'), 1)


class TestInCellLists(unittest.TestCase):
    """Tests for list blocks inside table cells (table-list attribute)."""

    def test_bullet_list_in_cell(self):
        """A bullet list inside a table cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Item 1'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-l1',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Item 2'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-l1',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<ul>', html)
        self.assertIn('</ul>', html)
        self.assertIn('<li>', html)
        self.assertEqual(html.count('<li>'), 2)
        self.assertIn('Item 1', html)
        self.assertIn('Item 2', html)

    def test_ordered_list_in_cell(self):
        """An ordered list inside a table cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'First'},
            {'insert': '\n', 'attributes': {
                'table-list': 'ordered',
                'table-list-container': {
                    'cellId': 'cell-ol',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Second'},
            {'insert': '\n', 'attributes': {
                'table-list': 'ordered',
                'table-list-container': {
                    'cellId': 'cell-ol',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<ol>', html)
        self.assertIn('</ol>', html)
        self.assertEqual(html.count('<li>'), 2)

    def test_list_in_cell_with_colspan(self):
        """A list in a cell that spans multiple columns."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'List item'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-ls',
                    'colspan': '2',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'A'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-a',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'B'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-b',
                'table-cell': {'data-row': 'row-2'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<ul>', html)
        self.assertIn('<li>', html)

    def test_list_with_data_row_in_container(self):
        """table-list-container may also contain data-row."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Item'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-x',
                    'data-row': 'row-1',
                    'colspan': '1',
                    'rowspan': '1',
                    'width': '200',
                    'height': '50',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<ul>', html)
        self.assertIn('Item', html)


class TestInlineFormatting(unittest.TestCase):
    """Tests for inline formatting within table cells."""

    def test_bold_in_cell(self):
        """Bold text within a table cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Bold text', 'attributes': {'bold': True}},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-b',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<strong>', html)
        self.assertIn('Bold text', html)

    def test_italic_in_cell(self):
        """Italic text within a table cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Italic text', 'attributes': {'italic': True}},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-i',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<em>', html)
        self.assertIn('Italic text', html)

    def test_link_in_cell(self):
        """A hyperlink within a table cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Click here', 'attributes': {'link': 'https://example.com'}},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-l',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('href="https://example.com"', html)
        self.assertIn('Click here', html)

    def test_mixed_inline_formatting(self):
        """Multiple inline formats in one cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Normal '},
            {'insert': 'bold', 'attributes': {'bold': True}},
            {'insert': ' and '},
            {'insert': 'italic', 'attributes': {'italic': True}},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-m',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Normal ', html)
        self.assertIn('<strong>bold</strong>', html)
        self.assertIn('<em>italic</em>', html)

    def test_colored_text_in_cell(self):
        """Text with color formatting in a cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Red text', 'attributes': {'color': '#ff0000'}},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-c',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('color: #ff0000', html)
        self.assertIn('Red text', html)

    def test_background_color_text_in_cell(self):
        """Text with background color in a cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Highlighted', 'attributes': {'background': '#ffff00'}},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-bg',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('background-color: #ffff00', html)
        self.assertIn('Highlighted', html)

    def test_strikethrough_in_cell(self):
        """Strikethrough text within a table cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Deleted', 'attributes': {'strike': True}},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-s',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<s>', html)
        self.assertIn('Deleted', html)

    def test_underline_in_cell(self):
        """Underlined text within a table cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Underlined', 'attributes': {'underline': True}},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-u',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<u>', html)
        self.assertIn('Underlined', html)


class TestMultipleParagraphsInCell(unittest.TestCase):
    """Tests for multiple paragraph blocks within a single cell."""

    def test_two_paragraphs_in_cell(self):
        """Two text paragraphs sharing the same cell ID."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Para 1'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-mp',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Para 2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-mp',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Para 1', html)
        self.assertIn('Para 2', html)
        # Both should be in the same cell
        self.assertEqual(html.count('<td>'), 1)

    def test_three_paragraphs_in_cell(self):
        """Three paragraphs in the same cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Line 1'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-3p',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Line 2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-3p',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Line 3'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-3p',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertEqual(html.count('<td>'), 1)
        self.assertIn('Line 1', html)
        self.assertIn('Line 2', html)
        self.assertIn('Line 3', html)


class TestMixedCellContent(unittest.TestCase):
    """Tests for cells containing a mix of paragraphs, headings, and lists."""

    def test_heading_then_paragraph(self):
        """A heading followed by a paragraph in the same cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Section'},
            {'insert': '\n', 'attributes': {
                'table-header': {'cellId': 'cell-mix', 'value': 2},
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Body text'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-mix',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Section', html)
        self.assertIn('Body text', html)
        self.assertEqual(html.count('<td>'), 1)

    def test_paragraph_then_list(self):
        """A paragraph followed by a list in the same cell."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Intro text'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-pl',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Item A'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-pl',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Item B'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-pl',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Intro text', html)
        self.assertIn('<ul>', html)
        self.assertIn('Item A', html)
        self.assertIn('Item B', html)


class TestCellStyleAttributes(unittest.TestCase):
    """Tests for cell-level styling via table-cell attributes."""

    def test_cell_with_width_and_height(self):
        """Cell with explicit width and height."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Sized'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-sz',
                'table-cell': {
                    'data-row': 'row-1',
                    'width': '200',
                    'height': '50',
                },
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Sized', html)
        self.assertIn('<table>', html)

    def test_cell_with_style_attribute(self):
        """Cell with inline style (background-color, border, etc.)."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Styled'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-st',
                'table-cell': {
                    'data-row': 'row-1',
                    'style': 'background-color: #f0f0f0; border-style: solid; border-width: 1px',
                },
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Styled', html)
        # The module should at least not crash on style attributes
        self.assertIn('<table>', html)

    def test_cell_with_all_attributes(self):
        """Cell with every possible attribute set."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Full'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-full',
                'table-cell': {
                    'data-row': 'row-1',
                    'width': '150',
                    'height': '40',
                    'colspan': '2',
                    'rowspan': '3',
                    'style': 'background-color: #ccc; border-color: #000; padding: 5px; text-align: center; vertical-align: middle',
                },
            }},
            # Additional cells to fill the grid
            {'insert': 'R1C3'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r1c3',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'R2C3'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r2c3',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'R3C1'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r3c1',
                'table-cell': {'data-row': 'row-3'},
            }},
            {'insert': 'R3C2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r3c2',
                'table-cell': {'data-row': 'row-3'},
            }},
            {'insert': 'R3C3'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r3c3',
                'table-cell': {'data-row': 'row-3'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('colspan="2"', html)
        self.assertIn('rowspan="3"', html)
        self.assertIn('Full', html)


class TestSurroundingContent(unittest.TestCase):
    """Tests for tables mixed with surrounding non-table content."""

    def test_text_before_table(self):
        """Text paragraph before a table."""
        ops = [
            {'insert': 'Introduction paragraph.\n'},
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Introduction paragraph.', html)
        self.assertIn('<table>', html)
        # Paragraph should come before table
        intro_pos = html.index('Introduction paragraph.')
        table_pos = html.index('<table>')
        self.assertLess(intro_pos, table_pos)

    def test_text_after_table(self):
        """Text paragraph after a table."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Conclusion paragraph.\n'},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)
        self.assertIn('Conclusion paragraph.', html)
        # Table should come before conclusion
        table_pos = html.index('</table>')
        conclusion_pos = html.index('Conclusion paragraph.')
        self.assertLess(table_pos, conclusion_pos)

    def test_text_before_and_after_table(self):
        """Text both before and after the table."""
        ops = [
            {'insert': 'Before.\n'},
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'After.\n'},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        before_pos = html.index('Before.')
        table_pos = html.index('<table>')
        after_pos = html.index('After.')
        self.assertLess(before_pos, table_pos)
        self.assertLess(table_pos, after_pos)

    def test_heading_before_table(self):
        """A heading block before the table."""
        ops = [
            {'insert': 'Table Title'},
            {'insert': '\n', 'attributes': {'header': 2}},
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<h2>', html)
        self.assertIn('Table Title', html)
        self.assertIn('<table>', html)


class TestTreeStructure(unittest.TestCase):
    """Tests for the internal document tree structure."""

    def _get_rows(self, table):
        """Extract TableBetter2RowBlock children from a table block."""
        return [b for b in table.contents if isinstance(b, TableBetter2RowBlock)]

    def _get_cells(self, row):
        """Extract TableBetter2CellBlock children from a row block."""
        return [c for c in row.contents if isinstance(c, TableBetter2CellBlock)]

    def test_basic_tree_structure(self):
        """Verify the tree structure for a simple 2x2 table."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'A'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-a',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'B'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-b',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'C'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-c',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': 'D'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-d',
                'table-cell': {'data-row': 'row-2'},
            }},
        ]
        t = _make_translator()
        doc = t.ops_to_internal_representation(ops)

        # Should have one table block (table-temporary creates it)
        table_blocks = [b for b in doc.contents if isinstance(b, TableBetter2Block)]
        self.assertEqual(len(table_blocks), 1, f"Expected 1 table block, got {len(table_blocks)}")

        table = table_blocks[0]
        # Two rows (filter out TextLine nodes from table-temporary's newline)
        rows = self._get_rows(table)
        self.assertEqual(len(rows), 2)

        # Two cells per row
        for row in rows:
            cells = self._get_cells(row)
            self.assertEqual(len(cells), 2)

    def test_heading_creates_heading_block(self):
        """table-header should create a TableBetter2CellHeadingBlock."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Title'},
            {'insert': '\n', 'attributes': {
                'table-header': {'cellId': 'cell-h', 'value': 1},
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        doc = t.ops_to_internal_representation(ops)
        table = [b for b in doc.contents if isinstance(b, TableBetter2Block)][0]
        rows = self._get_rows(table)
        self.assertEqual(len(rows), 1)
        cells = self._get_cells(rows[0])
        self.assertEqual(len(cells), 1)
        cell = cells[0]
        heading_blocks = [
            b for b in cell.contents if isinstance(b, TableBetter2CellHeadingBlock)
        ]
        self.assertGreaterEqual(len(heading_blocks), 1)

    def test_list_creates_list_container(self):
        """table-list should create a TableBetter2CellListContainerBlock."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Item'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-li',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        doc = t.ops_to_internal_representation(ops)
        table = [b for b in doc.contents if isinstance(b, TableBetter2Block)][0]
        rows = self._get_rows(table)
        self.assertEqual(len(rows), 1)
        cells = self._get_cells(rows[0])
        self.assertEqual(len(cells), 1)
        cell = cells[0]
        list_blocks = [
            b for b in cell.contents
            if isinstance(b, TableBetter2CellListContainerBlock)
        ]
        self.assertGreaterEqual(len(list_blocks), 1)

    def test_cell_ids_and_row_ids(self):
        """Verify cell_id and row_id are correctly stored on cell blocks."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'A'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-abc1',
                'table-cell': {'data-row': 'row-xyz1'},
            }},
        ]
        t = _make_translator()
        doc = t.ops_to_internal_representation(ops)
        table = [b for b in doc.contents if isinstance(b, TableBetter2Block)][0]
        rows = self._get_rows(table)
        cells = self._get_cells(rows[0])
        cell = cells[0]
        self.assertIsInstance(cell, TableBetter2CellBlock)
        self.assertEqual(cell.cell_id, 'cell-abc1')
        self.assertEqual(cell.row_id, 'row-xyz1')


class TestLatexOutput(unittest.TestCase):
    """Tests for LaTeX rendering of quill-table-better tables."""

    def test_basic_table_latex(self):
        """Basic table renders to LaTeX tabular environment."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'A'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-a',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'B'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-b',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        latex = t.translate_to_latex(ops)
        self.assertIn(r'\begin{tabular}', latex)
        self.assertIn(r'\end{tabular}', latex)
        self.assertIn('A', latex)
        self.assertIn('B', latex)

    def test_latex_hline(self):
        """LaTeX output should have hline separators between rows."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'R1'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r1',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'R2'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r2',
                'table-cell': {'data-row': 'row-2'},
            }},
        ]
        t = _make_translator()
        latex = t.translate_to_latex(ops)
        self.assertIn(r'\hline', latex)

    def test_list_in_cell_latex(self):
        """In-cell list renders to LaTeX itemize/enumerate."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Bullet'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-bl',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        latex = t.translate_to_latex(ops)
        self.assertIn(r'\begin{itemize}', latex)
        self.assertIn(r'\item', latex)

    def test_ordered_list_latex(self):
        """In-cell ordered list renders to LaTeX enumerate."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'First'},
            {'insert': '\n', 'attributes': {
                'table-list': 'ordered',
                'table-list-container': {
                    'cellId': 'cell-en',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        latex = t.translate_to_latex(ops)
        self.assertIn(r'\begin{enumerate}', latex)
        self.assertIn(r'\item', latex)


class TestEdgeCases(unittest.TestCase):
    """Edge cases and unusual delta formats."""

    def test_randomized_cell_ids(self):
        """Cell IDs in the typical random format (cell-XXXX)."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Data'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-a1b2',
                'table-cell': {'data-row': 'row-c3d4'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Data', html)
        self.assertIn('<table>', html)

    def test_no_colspan_rowspan_keys(self):
        """Cell without colspan/rowspan keys at all (not even None)."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Plain'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-p',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertNotIn('colspan', html)
        self.assertNotIn('rowspan', html)
        self.assertIn('Plain', html)

    def test_none_colspan_rowspan(self):
        """Cell with explicit None for colspan and rowspan."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Null spans'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-ns',
                'table-cell': {
                    'data-row': 'row-1',
                    'colspan': None,
                    'rowspan': None,
                },
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertNotIn('colspan', html)
        self.assertNotIn('rowspan', html)

    def test_special_characters_in_cells(self):
        """HTML special characters in cell content are escaped."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': '<script>alert("xss")</script>'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-xss',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertNotIn('<script>', html)
        self.assertIn('&lt;script&gt;', html)

    def test_large_table(self):
        """A larger table (10x5) processes without error."""
        ops = [{'insert': '\n', 'attributes': {'table-temporary': True}}]
        for row in range(1, 11):
            for col in range(1, 6):
                ops.extend([
                    {'insert': f'R{row}C{col}'},
                    {'insert': '\n', 'attributes': {
                        'table-cell-block': f'cell-r{row}c{col}',
                        'table-cell': {'data-row': f'row-{row}'},
                    }},
                ])
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertEqual(html.count('<tr>'), 10)
        self.assertEqual(html.count('<td>'), 50)

    def test_unicode_content_in_cells(self):
        """Unicode content in table cells."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Héllo Wörld'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-u1',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': '日本語テスト'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-u2',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Héllo Wörld', html)
        self.assertIn('日本語テスト', html)

    def test_table_temporary_with_string_true(self):
        """table-temporary with string 'true' instead of boolean True."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': 'true'}},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)
        self.assertIn('Cell', html)


class TestCellBlockRealWorldFormat(unittest.TestCase):
    """Tests using realistic delta ops as generated by quill-table-better."""

    def test_realistic_simple_table(self):
        """A realistic 3x3 table as quill-table-better would produce it."""
        ops = [
            {'insert': '\n', 'attributes': {
                'table-temporary': {
                    'style': 'width: 100%',
                    'data-class': 'ql-table-better',
                }
            }},
            {'insert': 'Name'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-a1b2',
                'table-cell': {
                    'data-row': 'row-x1y2',
                    'width': '72',
                    'height': '24',
                },
            }},
            {'insert': 'Age'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-c3d4',
                'table-cell': {
                    'data-row': 'row-x1y2',
                    'width': '72',
                    'height': '24',
                },
            }},
            {'insert': 'City'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-e5f6',
                'table-cell': {
                    'data-row': 'row-x1y2',
                    'width': '72',
                    'height': '24',
                },
            }},
            {'insert': 'Alice'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-g7h8',
                'table-cell': {
                    'data-row': 'row-m5n6',
                    'width': '72',
                    'height': '24',
                },
            }},
            {'insert': '30'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-i9j0',
                'table-cell': {
                    'data-row': 'row-m5n6',
                    'width': '72',
                    'height': '24',
                },
            }},
            {'insert': 'London'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-k1l2',
                'table-cell': {
                    'data-row': 'row-m5n6',
                    'width': '72',
                    'height': '24',
                },
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertEqual(html.count('<tr>'), 2)
        self.assertEqual(html.count('<td>'), 6)
        for text in ('Name', 'Age', 'City', 'Alice', '30', 'London'):
            self.assertIn(text, html)

    def test_realistic_merged_cells(self):
        """Realistic merged-cell table (header spanning full width)."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            # Row 1: header spanning 3 columns
            {'insert': 'Monthly Report'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-hdr',
                'table-cell': {
                    'data-row': 'row-hdr',
                    'colspan': '3',
                    'style': 'background-color: #4472c4; text-align: center',
                },
            }},
            # Row 2: column headers
            {'insert': 'Month'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-h1',
                'table-cell': {'data-row': 'row-cols'},
            }},
            {'insert': 'Revenue'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-h2',
                'table-cell': {'data-row': 'row-cols'},
            }},
            {'insert': 'Growth'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-h3',
                'table-cell': {'data-row': 'row-cols'},
            }},
            # Row 3: data
            {'insert': 'January'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-d1',
                'table-cell': {'data-row': 'row-data'},
            }},
            {'insert': '$50,000'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-d2',
                'table-cell': {'data-row': 'row-data'},
            }},
            {'insert': '5%'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-d3',
                'table-cell': {'data-row': 'row-data'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('colspan="3"', html)
        self.assertIn('Monthly Report', html)
        self.assertEqual(html.count('<tr>'), 3)

    def test_realistic_with_heading_and_list(self):
        """Realistic table with heading and list inside cells."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            # Cell with heading
            {'insert': 'Features'},
            {'insert': '\n', 'attributes': {
                'table-header': {'cellId': 'cell-feat', 'value': 3},
                'table-cell': {'data-row': 'row-1'},
            }},
            # Cell with list
            {'insert': 'Fast'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-list',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Reliable'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-list',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Secure'},
            {'insert': '\n', 'attributes': {
                'table-list': 'bullet',
                'table-list-container': {
                    'cellId': 'cell-list',
                    'colspan': '1',
                    'rowspan': '1',
                },
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('Features', html)
        self.assertIn('<ul>', html)
        self.assertEqual(html.count('<li>'), 3)
        for item in ('Fast', 'Reliable', 'Secure'):
            self.assertIn(item, html)

    def test_realistic_document_with_table(self):
        """A full document with heading, paragraph, table, and conclusion."""
        ops = [
            # Heading
            {'insert': 'Quarterly Report'},
            {'insert': '\n', 'attributes': {'header': 1}},
            # Introduction paragraph
            {'insert': 'Here are the results for Q1.\n'},
            # Table
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Metric'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-m',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Value'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-v',
                'table-cell': {'data-row': 'row-1'},
            }},
            {'insert': 'Revenue'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-r',
                'table-cell': {'data-row': 'row-2'},
            }},
            {'insert': '$1M'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-rv',
                'table-cell': {'data-row': 'row-2'},
            }},
            # Conclusion
            {'insert': 'Results look promising.\n'},
        ]
        t = _make_translator()
        html = t.translate_to_html(ops)
        self.assertIn('<h1>', html)
        self.assertIn('Quarterly Report', html)
        self.assertIn('Here are the results for Q1.', html)
        self.assertIn('<table>', html)
        self.assertIn('Results look promising.', html)
        # Verify ordering
        h1_pos = html.index('<h1>')
        intro_pos = html.index('Here are the results')
        table_pos = html.index('<table>')
        conclusion_pos = html.index('Results look promising')
        self.assertLess(h1_pos, intro_pos)
        self.assertLess(intro_pos, table_pos)
        self.assertLess(table_pos, conclusion_pos)


class TestModuleRegistration(unittest.TestCase):
    """Tests that the TableBetterModule integrates properly."""

    def test_module_registers_tests(self):
        """The module's test functions are registered in the translator."""
        t = _make_translator()
        test_names = [f.__name__ for f in t.block_registry.keys()]
        self.assertIn('new_table_test', test_names)
        self.assertIn('table_better_cell_test', test_names)

    def test_module_does_not_conflict_with_other_table_modules(self):
        """TableBetterModule doesn't conflict with existing table modules."""
        t = _make_translator()
        # Test standard quill 2.x table format still works
        ops = [
            {'insert': '1'}, {'attributes': {'table': 'row-1'}, 'insert': '\n'},
            {'insert': '2'}, {'attributes': {'table': 'row-1'}, 'insert': '\n'},
        ]
        html = t.translate_to_html(ops)
        self.assertIn('<table>', html)
        self.assertIn('1', html)
        self.assertIn('2', html)

    def test_table_temporary_not_matched_as_regular_block(self):
        """table-temporary ops must not be matched by header/code/etc. tests."""
        ops = [
            {'insert': '\n', 'attributes': {'table-temporary': True}},
            {'insert': 'Cell'},
            {'insert': '\n', 'attributes': {
                'table-cell-block': 'cell-1',
                'table-cell': {'data-row': 'row-1'},
            }},
        ]
        t = _make_translator()
        doc = t.ops_to_internal_representation(ops)
        table_blocks = [b for b in doc.contents if isinstance(b, TableBetter2Block)]
        self.assertEqual(len(table_blocks), 1)


if __name__ == '__main__':
    unittest.main()
